[buildPlans.iosevka-sf]
family = "Iosevka SF"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true
no-ligation = true
export-glyph-names = false
cap = 705
xHeight = 526

[buildPlans.iosevka-sf.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-q = "crossing"
f = "flat-hook-crossbar-at-x-height"
j = "flat-hook-serifed"
r = "hookless-serifed"
t = "flat-hook-short-neck2"
y = "straight-turn"
long-s = "flat-hook"
lower-alpha = "tailed-barred"
lower-lambda = "straight-turn"
cyrl-capital-u = "straight-turn"
zero = "slashed"
one = "base"
two = "straight-neck"
five = "oblique-upper-left-bar"
eight = "two-circles"
asterisk = "hex-low"
underscore = "low"
caret = "high"
brace = "curly"
number-sign = "slanted"
at = "fourfold-solid-inner"
cent = "open"
percent = "rings-continuous-slash"

[buildPlans.iosevka-sf.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-sf.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-sf.widths.ultracondensed]
shape = 416
menu = 1
css = "ultra-condensed"

[buildPlans.iosevka-sf.widths.extracondensed]
shape = 456
menu = 2
css = "extra-condensed"

[buildPlans.iosevka-sf.widths.condensed]
shape = 497
menu = 3
css = "condensed"

[buildPlans.iosevka-sf.widths.semicondensed]
shape = 537
menu = 4
css = "semi-condensed"

[buildPlans.iosevka-sf.widths.normal]
shape = 578
menu = 5
css = "normal"
